# Generated by Django 4.2.4 on 2023-08-23 07:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adminstaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(default='booran', max_length=100)),
                ('mobile_number', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'adminstaff',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('childName', models.CharField(default='null', max_length=100)),
                ('childRollNo', models.CharField(default='null', max_length=100)),
                ('parentId', models.CharField(default='null', max_length=100)),
                ('phoneNo', models.CharField(default='null', max_length=10)),
                ('address', models.CharField(default='null', max_length=100)),
                ('email', models.EmailField(default='null', max_length=100)),
                ('password', models.CharField(default='null', max_length=100)),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to='parent_profile_pics/')),
            ],
            options={
                'verbose_name_plural': 'parent',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('std', models.CharField(default='null', max_length=100)),
                ('rollNo', models.CharField(default='null', max_length=100)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('phoneNo', models.CharField(default='null', max_length=10)),
                ('parentName', models.CharField(default='null', max_length=100)),
                ('address', models.CharField(default='null', max_length=100)),
                ('email', models.EmailField(default='null', max_length=100)),
                ('password', models.CharField(default='null', max_length=100)),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to='student_profile_pics/')),
            ],
            options={
                'verbose_name_plural': 'student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('subjectName', models.CharField(default='', max_length=100)),
                ('teacherId', models.CharField(default='null', max_length=100)),
                ('phoneNo', models.CharField(default='null', max_length=10)),
                ('qualification', models.CharField(default='null', max_length=100)),
                ('address', models.CharField(default='null', max_length=100)),
                ('email', models.EmailField(default='null', max_length=100)),
                ('password', models.CharField(default='null', max_length=100)),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to='teacher_profile_pics/')),
                ('classTaught', models.CharField(default='null', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='TeacherStudentChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_text', models.TextField()),
                ('msg_from', models.CharField(max_length=100)),
                ('msg_time', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
        ),
    ]
